apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-redis
  name: edgex-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
    nodePort: 6379
  selector:
    org.edgexfoundry.service: edgex-redis
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-redis
  name: edgex-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-redis
    spec:
      containers:
      - name: edgex-redis
        image: redis:5.0.8-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        livenessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 5
        volumeMounts:
          - mountPath: /data
            name: db-data
      hostname: edgex-redis
      restartPolicy: Always
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
