apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-data
  name: edgex-core-data
spec:
  ports:
  - name: "48080"
    port: 48080
    targetPort: 48080
    nodePort: 48080
  - name: "5563"
    port: 5563
    targetPort: 5563
    nodePort: 5563
  selector:
    org.edgexfoundry.service: edgex-core-data
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-data
  name: edgex-core-data
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-data
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-data
    spec:
      containers:
      - name: edgex-core-data
        image: edgexfoundry/docker-core-data-go:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 48080
        - containerPort: 5563
        env:
        - name: Service_Host
          value: edgex-core-data
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48080
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48080
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      hostname: edgex-core-data
      restartPolicy: Always
