apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  name: edgex-sys-mgmt-agent
spec:
  ports:
  - name: "48090"
    port: 48090
    targetPort: 48090
    nodePort: 48090
  selector:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-sys-mgmt-agent
  name: edgex-sys-mgmt-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-sys-mgmt-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-sys-mgmt-agent
    spec:
      containers:
      - name: edgex-sys-mgmt-agent
        image: edgexfoundry/docker-sys-mgmt-agent-go:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 48090
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: Service_Host
          value: edgex-sys-mgmt-agent
        - name: ExecutorPath
          value: "/sys-mgmt-executor"
        - name: MetricsMechanism
          value: "executor"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48090
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48090
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      hostname: edgex-sys-mgmt-agent
      restartPolicy: Always
