apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-command
  name: edgex-core-command
spec:
  ports:
  - name: "48082"
    port: 48082
    targetPort: 48082
    nodePort: 48082
  selector:
    org.edgexfoundry.service: edgex-core-command
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-command
  name: edgex-core-command
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-command
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-command
    spec:
      containers:
      - name: edgex-core-command
        image: edgexfoundry/docker-core-command-go:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 48082
        env:
        - name: Service_Host
          value: edgex-core-command
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48082
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48082
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
      hostname: edgex-core-command
      restartPolicy: Always
