apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  ports:
  - name: "8400"
    port: 8400
    targetPort: 8400
    nodePort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
    nodePort: 8500
  selector:
    org.edgexfoundry.service: edgex-core-consul
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-core-consul
  name: edgex-core-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-core-consul
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-core-consul
    spec:
      containers:
      - name: edgex-core-consul
        image: edgexfoundry/docker-edgex-consul:1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8400
        - containerPort: 8500
        envFrom:
        - configMapRef:
            name: edgex-common-variables
        env:
        - name: EDGEX_DB
          value: "redis"
        - name: EDGEX_SECURE
          value: "false"
        livenessProbe:
          tcpSocket:
            port: 8500
          periodSeconds: 5
        startupProbe:
          tcpSocket:
            port: 8500
          initialDelaySeconds: 1
          failureThreshold: 30
          periodSeconds: 5
        volumeMounts:
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      hostname: edgex-core-consul
      restartPolicy: Always
      volumes:
      - name: consul-config
        persistentVolumeClaim:
          claimName: consul-config
      - name: consul-data
        persistentVolumeClaim:
          claimName: consul-data
