apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-rulesengine
  name: edgex-support-rulesengine
spec:
  ports:
  - name: "48075"
    port: 48075
    targetPort: 48075
    nodePort: 48075
  selector:
    org.edgexfoundry.service: edgex-support-rulesengine
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: edgex-support-rulesengine
  name: edgex-support-rulesengine
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: edgex-support-rulesengine
  strategy: {}
  template:
    metadata:
      labels:
        org.edgexfoundry.service: edgex-support-rulesengine
    spec:
      containers:
      - name: edgex-support-rulesengine
        image: emqx/kuiper:0.4.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 48075
        - containerPort: 20498
        env:
#        - name: KUIPER_DEBUG
#          value: "true"
        - name: KUIPER_CONSOLE_LOG
          value: "true"
        - name: KUIPER_REST_PORT
          value: "48075"
        - name: EDGEX_SERVER
          value: edgex-app-service-configurable-rules
        - name: EDGEX_SERVICE_SERVER
          value: http://edgex-core-data:48080
        - name: EDGEX_TOPIC
          value: "events"
        - name: EDGEX_PROTOCOL
          value: "tcp"
        - name: EDGEX_PORT
          value: "5566"
        livenessProbe:
          tcpSocket:
            port: 48075
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 48075
          periodSeconds: 5
      hostname: edgex-support-rulesengine
      restartPolicy: Always
